/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.zain.states.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Statess service. Represents a row in the &quot;Zain_Statess&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.zain.states.model.impl.StatessModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.zain.states.model.impl.StatessImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Statess
 * @generated
 */
@ProviderType
public interface StatessModel extends BaseModel<Statess> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a statess model instance should use the {@link Statess} interface instead.
	 */

	/**
	 * Returns the primary key of this statess.
	 *
	 * @return the primary key of this statess
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this statess.
	 *
	 * @param primaryKey the primary key of this statess
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the uuid of this statess.
	 *
	 * @return the uuid of this statess
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this statess.
	 *
	 * @param uuid the uuid of this statess
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this statess.
	 *
	 * @return the ID of this statess
	 */
	public int getId();

	/**
	 * Sets the ID of this statess.
	 *
	 * @param id the ID of this statess
	 */
	public void setId(int id);

	/**
	 * Returns the name of this statess.
	 *
	 * @return the name of this statess
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this statess.
	 *
	 * @param name the name of this statess
	 */
	public void setName(String name);

	/**
	 * Returns the country_id of this statess.
	 *
	 * @return the country_id of this statess
	 */
	public int getCountry_id();

	/**
	 * Sets the country_id of this statess.
	 *
	 * @param country_id the country_id of this statess
	 */
	public void setCountry_id(int country_id);

}