/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.zain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the City service. Represents a row in the &quot;Zain_City&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.zain.model.impl.CityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.zain.model.impl.CityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see City
 * @generated
 */
@ProviderType
public interface CityModel
	extends BaseModel<City>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a city model instance should use the {@link City} interface instead.
	 */

	/**
	 * Returns the primary key of this city.
	 *
	 * @return the primary key of this city
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this city.
	 *
	 * @param primaryKey the primary key of this city
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the uuid of this city.
	 *
	 * @return the uuid of this city
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this city.
	 *
	 * @param uuid the uuid of this city
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the group ID of this city.
	 *
	 * @return the group ID of this city
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this city.
	 *
	 * @param groupId the group ID of this city
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this city.
	 *
	 * @return the company ID of this city
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this city.
	 *
	 * @param companyId the company ID of this city
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this city.
	 *
	 * @return the user ID of this city
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this city.
	 *
	 * @param userId the user ID of this city
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this city.
	 *
	 * @return the user uuid of this city
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this city.
	 *
	 * @param userUuid the user uuid of this city
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this city.
	 *
	 * @return the user name of this city
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this city.
	 *
	 * @param userName the user name of this city
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this city.
	 *
	 * @return the create date of this city
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this city.
	 *
	 * @param createDate the create date of this city
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this city.
	 *
	 * @return the modified date of this city
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this city.
	 *
	 * @param modifiedDate the modified date of this city
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ID of this city.
	 *
	 * @return the ID of this city
	 */
	public int getId();

	/**
	 * Sets the ID of this city.
	 *
	 * @param id the ID of this city
	 */
	public void setId(int id);

	/**
	 * Returns the city of this city.
	 *
	 * @return the city of this city
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this city.
	 *
	 * @param city the city of this city
	 */
	public void setCity(String city);

	/**
	 * Returns the state_id of this city.
	 *
	 * @return the state_id of this city
	 */
	public int getState_id();

	/**
	 * Sets the state_id of this city.
	 *
	 * @param state_id the state_id of this city
	 */
	public void setState_id(int state_id);

}