/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.zain.practice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the normal service. Represents a row in the &quot;Zain_normal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.zain.practice.model.impl.normalModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.zain.practice.model.impl.normalImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see normal
 * @generated
 */
@ProviderType
public interface normalModel
	extends BaseModel<normal>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a normal model instance should use the {@link normal} interface instead.
	 */

	/**
	 * Returns the primary key of this normal.
	 *
	 * @return the primary key of this normal
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this normal.
	 *
	 * @param primaryKey the primary key of this normal
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sample ID of this normal.
	 *
	 * @return the sample ID of this normal
	 */
	public long getSampleId();

	/**
	 * Sets the sample ID of this normal.
	 *
	 * @param sampleId the sample ID of this normal
	 */
	public void setSampleId(long sampleId);

	/**
	 * Returns the group ID of this normal.
	 *
	 * @return the group ID of this normal
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this normal.
	 *
	 * @param groupId the group ID of this normal
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this normal.
	 *
	 * @return the company ID of this normal
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this normal.
	 *
	 * @param companyId the company ID of this normal
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this normal.
	 *
	 * @return the user ID of this normal
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this normal.
	 *
	 * @param userId the user ID of this normal
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this normal.
	 *
	 * @return the user uuid of this normal
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this normal.
	 *
	 * @param userUuid the user uuid of this normal
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this normal.
	 *
	 * @return the user name of this normal
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this normal.
	 *
	 * @param userName the user name of this normal
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this normal.
	 *
	 * @return the create date of this normal
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this normal.
	 *
	 * @param createDate the create date of this normal
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this normal.
	 *
	 * @return the modified date of this normal
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this normal.
	 *
	 * @param modifiedDate the modified date of this normal
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this normal.
	 *
	 * @return the name of this normal
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this normal.
	 *
	 * @param name the name of this normal
	 */
	public void setName(String name);

	/**
	 * Returns the catalog of this normal.
	 *
	 * @return the catalog of this normal
	 */
	@AutoEscape
	public String getCatalog();

	/**
	 * Sets the catalog of this normal.
	 *
	 * @param catalog the catalog of this normal
	 */
	public void setCatalog(String catalog);

	/**
	 * Returns the governorate of this normal.
	 *
	 * @return the governorate of this normal
	 */
	@AutoEscape
	public String getGovernorate();

	/**
	 * Sets the governorate of this normal.
	 *
	 * @param governorate the governorate of this normal
	 */
	public void setGovernorate(String governorate);

	/**
	 * Returns the areazone of this normal.
	 *
	 * @return the areazone of this normal
	 */
	@AutoEscape
	public String getAreazone();

	/**
	 * Sets the areazone of this normal.
	 *
	 * @param areazone the areazone of this normal
	 */
	public void setAreazone(String areazone);

}